import { Timestamp, UUID } from "./Fields";

/**
 * webhook receive from aws sns
 */
export const INCOMING_WEBHOOK_EVENT_PROVIDER_AWS_SNS = "aws_sns";

/**
 * record.provider = 'aws_sns' AND payload.Type = 'SubscriptionConfirmation'
 */
export const AWS_SNS_WEBHOOK_EVENT_TYPE_SUBSCRIPTION_CONFIRMATION =
    "subscription_confirmation";

/**
 * record.provider = 'aws_sns' AND payload.Type = 'UnsubscribeConfirmation'
 */
export const AWS_SNS_WEBHOOK_EVENT_TYPE_UNSUBSCRIPTION_CONFIRMATION =
    "unsubscribe_confirmation";

/**
 * record.provider = 'aws_sns' AND payload.Type = 'Notification'
 */
export const AWS_SNS_WEBHOOK_EVENT_TYPE_NOTIFICATION = "notification";

/**
 * record.provider = 'aws_sns' AND payload.Type = 'ses_bounce'
 */
export const AWS_SNS_WEBHOOK_EVENT_TYPE_SES_BOUNCE = "ses_bounce";
/**
 * record.provider = 'aws_sns' AND payload.Type = 'ses_complaint'
 */
export const AWS_SNS_WEBHOOK_EVENT_TYPE_SES_COMPLAINT = "ses_complaint";
/**
 * record.provider = 'aws_sns' AND payload.Type = 'ses_delivery'
 */
export const AWS_SNS_WEBHOOK_EVENT_TYPE_SES_DELIVERY = "ses_delivery";
/**
 * record.provider = 'aws_sns' AND payload.Type = 'ses_send'
 */
export const AWS_SNS_WEBHOOK_EVENT_TYPE_SES_SEND = "ses_send";
/**
 * record.provider = 'aws_sns' AND payload.Type is unhandled
 */
export const AWS_SNS_WEBHOOK_EVENT_TYPE_SES_UNKNOWN = "ses_unknown";

/**
 * fallback situation for logging the payload, while allow later decision
 * - record.external_id =  null
 */
export const AWS_SNS_WEBHOOK_EVENT_TYPE_UNKNOWN = "unknown";

export interface IncomingWebhookEvent {
    /**
     * Unique identifier for the event (UUID).
     * Generated by the database.
     */
    id: UUID;

    /**
     * Source of the webhook event.
     * - "aws_sns": {@link INCOMING_WEBHOOK_EVENT_PROVIDER_AWS_SNS}
     */
    provider: string;

    /**
     * Normalized event type for internal processing.
     * enum:
     * - "subscription_confirmation"    : {@link AWS_SNS_WEBHOOK_EVENT_TYPE_SUBSCRIPTION_CONFIRMATION}
     * - "notification"                 : {@link AWS_SNS_WEBHOOK_EVENT_TYPE_NOTIFICATION}
     * - "ses_bounce"                   : {@link AWS_SNS_WEBHOOK_EVENT_TYPE_SES_BOUNCE}
     * - "ses_complaint"                : {@link AWS_SNS_WEBHOOK_EVENT_TYPE_SES_COMPLAINT}
     * - "ses_delivery"                 : {@link AWS_SNS_WEBHOOK_EVENT_TYPE_SES_DELIVERY}
     * - "ses_send"                     : {@link AWS_SNS_WEBHOOK_EVENT_TYPE_SES_SEND}
     * - "ses_unknown"                  : {@link AWS_SNS_WEBHOOK_EVENT_TYPE_SES_UNKNOWN}
     * - "unknown"                      : {@link AWS_SNS_WEBHOOK_EVENT_TYPE_UNKNOWN}
     */
    event_type: string;

    /**
     * External unique identifier from the provider.
     * For AWS SNS, this is typically MessageId.
     * Used for deduplication and idempotency.
     */
    external_id: string | null;

    /**
     * Raw webhook payload as received.
     * Stored as JSON for debugging and reprocessing.
     */
    payload: Record<string, any>;

    /**
     * Processing status of the event.
     * - "pending": waiting to be processed
     * - "processing": currently being handled by a worker
     * - "processed": successfully handled
     * - "failed": permanently failed after retries
     */
    status: "pending" | "processing" | "processed" | "failed";

    /**
     * Number of processing attempts made.
     * Incremented on each failure.
     */
    attempts: number;

    /**
     * Timestamp when the event was created (ingested).
     */
    created_at: string;

    /**
     * Timestamp when processing completed successfully.
     * Null if not processed yet or failed.
     */
    processed_at: Timestamp;
}
